### ISSUE TITLE
https://r2lab.inria.fr/run.md update request

### ISSUE THREAD

**Issue by turletti** [fit-r2lab/r2lab.inria.fr#9]
It would be great to include new nodes in the map as they can send waves in the room.

pc01 with usrp b210 (called usrp01 for rhubarbe pdu) replaces node fit04
at the same location, 2 new UEs qhat01 and qhat02 are installed

pc02 with usrp b210 (called usrp02 for rhubarbe pdu) replaces node fit13
at the same location, UE qhat03 is installed

pc01/02 are mini PCs used as 5G gNB (MINIS FORUM ref UM690, see https://www.amazon.fr/MINIS-FORUM-UM690-32-512/dp/B0BP1N78R7)

qhat01/02/03 are used as UEs, composed with Raspberry Pi4 with 5G Quectel RM 500Q-GL

As fit04 and fit13 and their USRP devices are no more there, we could for instance replace the circle for fit with a square to represent a pc. We can keep the same symbol for usrp devices attached to pc and for qhat -- indeed this symbol is already used for quectel devices, limesdr. It seems there is room to place 3 symbols on top of each square. I don't think it's a good idea to add them with RRUs at the left of the map as those devices are not RRUs and similar to the other devices.

I am not sure if it is useful to add them in the database for the sidecar r2lab client and how complex it is to make the changes. The most important for me is to be able to check in the map the state of those new devices.

**Comment by parmentelat** [comment]
hi there

before I start coding anything, I'd like to make sure I have captured it properly

so here's a rough mockup of how things could like
of course the labels and lines will be shown only on mouse hover - I mean like now - but this allows me to have a better global view
in terms of ON/OFF animation:
- the squares for pc1 will reflect the status reported by rhubarbe pdu status pc01 
- the gnu logo attached to pc1 (resp pc2) (formerly node4 and resp. node 13) will reflect the status reported by rhubarbe pdu status usrp01 - resp usrp02
- the 3 other new antennas will reflect e.g. rhubarbe pdu status qhat01 .. 03

my understanding is the software unning in pc01 and pc02 is always the same, so no need to display ubuntu/fedora labels, right ? 
in this case maybe I'll just show numbers 1 and 2 in blue, and put a square around when they are up; or something similar...

please let me know if that's a correct interpretation of your requirements

<img width="1290" alt="r2lab-mockup-01" src="https://github.com/fit-r2lab/r2lab.inria.fr/assets/4519227/779b11ae-eaa8-4609-b465-9b65dddfd787">

**Comment by parmentelat** [comment]
the feature is online as of jan. 9 2024
